baseURL = 'cupofsquid.netlify.app'
languageCode = 'en-us'
title = 'Cup of Squid'
theme = 'bb'

[params]
    subtitle = "~musings and folly~"
    dateFmt = "02.01.2006 15:04"

[menu]
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/page/about/"
        weight = 1

  [[menu.main]]
        identifier = "art"
        name = "Art"
        url = "/page/art/"
        weight = 2

  [[menu.main]]
        identifier = "writing"
        name = "Writing"
        url = "/page/writing/"
        weight = 3


# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/ej-mitchell"
        weight = 1 

  [[menu.footer]]
        name = "Mastodon"
        url = "https://merveilles.town/@eejum"
        weight = 2 

  [[menu.footer]]
        name = "Buy me a coffee"
        url = "https://ko-fi.com/B0B86RY0J"
        weight = 3
